### ISSUE TITLE
window does not open

### ISSUE THREAD

**Issue by jahlomp** [breach/node-thrust#11]
When I run the following code with node-thrust, the window does not open.
I'm using MS Windows

`require('node-thrust')(function(err, api) { 
  api.window({ root_url: 'https://breach.cc' }).show();
});`

this is what i get on the command line

`[2015-01-07T11:15:53.779Z] SPAWING c:\Users\ACARE\Desktop\lily\node_modules\node-thrust\vendor\thrust\thrust_shell`

**Comment by alspore** [comment]
I'm getting the same output in Debian along with this.

```
events.js:72
    throw er; // Unhandled 'error' event

Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

**Comment by empirefx** [comment]
Got same error in debian wheezy(linux 3.2.0-4-amd64, node v0.10.35, npm 2.2.0, node-thrust 0.7.6-rc.1).

**Comment by zodern** [comment]
I am getting the same error in OSX 10.7.5. node 0.10.32 and node-thrust 0.7.6-rc.1.

**Comment by xzure** [comment]
Albeit an issue over two and a half years old, this is still an issue. 

The following will resolve the issue for all three of the supported platforms.


```
let thrust = require('node-thrust')((err, api) => {
    let w = api.window({ root_url: '...' });
    w.show()
}, {
  let binariesPath = () => {
    switch ( process.platform ) {
      case 'darwin' :
        return './node_modules/node-thrust/vendor/thrust/ThrustShell.app/Contents/MacOS/ThrustShell'
        break;
      case 'win32' :
        return '\\node_modules\\node-thrust\\vendor\\thrust\\thrust_shell.exe'
        break;
      case 'linux' :
        return './node_modules/node-thrust/vendor/thrust/thrust_shell'
        break;
    }
  }()

  exec_path: binariesPath
});
```
