### ISSUE TITLE
Possible post-install issue.

### ISSUE THREAD

**Issue by miketheprogrammer** [breach/node-thrust#6]
## Michaels-MacBook-Pro-2:get-referred-v2 mhernandez$ npm install -g https://gist.github.com/morganrallen/f07f59802884bcdcad4a/download

> node-thrust@0.1.5 postinstall /Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust
> node scripts/bootstrap.js

Creating: /Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust
Downloading: https://github.com/breach/thrust/releases/download/v0.7.4/thrust-v0.7.4-darwin-x64.zip
................
Extracting /Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/thrust-v0.7.4-darwin-x64.zip
stderr: [/Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/thrust-v0.7.4-darwin-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/thrust-v0.7.4-darwin-x64.zip or
        /Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/thrust-v0.7.4-darwin-x64.zip.zip, and cannot find /Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/thrust-v0.7.4-darwin-x64.zip.ZIP, period.

[2014-11-10T17:10:08.766Z] *********************************************
[2014-11-10T17:10:08.767Z] ERROR: Extraction failed with code: 9
[2014-11-10T17:10:08.767Z] *********************************************
[2014-11-10T17:10:08.769Z] Error: Extraction failed with code: 9
[2014-11-10T17:10:08.769Z]     at Object.exports.err (/Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust/lib/common.js:311:13)
[2014-11-10T17:10:08.769Z]     at ChildProcess.<anonymous> (/Users/mhernandez/.nvm/v0.11.14/lib/node_modules/jankybrowser/node_modules/node-thrust/scripts/bootstrap.js:129:29)
[2014-11-10T17:10:08.769Z]     at ChildProcess.emit (events.js:118:17)
[2014-11-10T17:10:08.769Z]     at maybeClose (child_process.js:1000:16)
[2014-11-10T17:10:08.769Z]     at Socket.<anonymous> (child_process.js:1168:11)
[2014-11-10T17:10:08.769Z]     at Socket.emit (events.js:107:17)
[2014-11-10T17:10:08.769Z]     at Pipe.close (net.js:461:12)
[2014-11-10T17:10:08.769Z] ---------------------------------------------

**Comment by spolu** [comment]
Thanks will investigate!

**Comment by spolu** [comment]
No additional report of this. closing

**Comment by hoppula** [comment]
Encountering similar error with nvm installed node v0.11.14:

> node-thrust@0.7.5-rc2 postinstall /Users/lari/nvm/v0.11.14/lib/node_modules/node-thrust
> node scripts/bootstrap.js

/Users/lari/nvm/v0.11.14/lib/node_modules/node-thrust/vendor/thrust/.version
Creating: /Users/lari/nvm/v0.11.14/lib/node_modules/node-thrust/vendor/thrust
Downloading: https://github.com/breach/thrust/releases/download/v0.7.5/thrust-v0.7.5-darwin-x64.zip
.....................
Extracting /Users/lari/nvm/v0.11.14/lib/node_modules/node-thrust/vendor/thrust/thrust-v0.7.5-darwin-x64.zip
[2014-11-24T14:05:54.208Z] *********************************************
[2014-11-24T14:05:54.208Z] ERROR: Extraction failed with code: 9
[2014-11-24T14:05:54.209Z] *********************************************
[2014-11-24T14:05:54.215Z] Error: Extraction failed with code: 9
[2014-11-24T14:05:54.215Z]     at Object.exports.err (/Users/lari/nvm/v0.11.14/lib/node_modules/node-thrust/lib/common.js:311:13)
[2014-11-24T14:05:54.215Z]     at ChildProcess.<anonymous> (/Users/lari/nvm/v0.11.14/lib/node_modules/node-thrust/scripts/bootstrap.js:125:31)
[2014-11-24T14:05:54.215Z]     at ChildProcess.emit (events.js:118:17)
[2014-11-24T14:05:54.215Z]     at maybeClose (child_process.js:1000:16)
[2014-11-24T14:05:54.215Z]     at Socket.<anonymous> (child_process.js:1168:11)
[2014-11-24T14:05:54.215Z]     at Socket.emit (events.js:107:17)
[2014-11-24T14:05:54.215Z]     at Pipe.close (net.js:461:12)
[2014-11-24T14:05:54.216Z] ---------------------------------------------

**Comment by spolu** [comment]
Code 9 might mean that the file to be extracted was not found. 
You can try to print the path used here: https://github.com/breach/node-thrust/blob/master/scripts/bootstrap.js#L118
And compare it to the download path / check if it exists.

To do so you can directly modify the file under `/Users/lari/nvm/v0.11.14/lib/node_modules/node-thrust/` and run `npm install` or `node scripts/bootstrap.js` from there.

**Comment by dxnn** [comment]
I'm getting a similar error, but in my case it's due to THRUST_RELEASE_PLATFORM being set to undefined. I hardcoded THRUST_RELEASE_URL to https://github.com/breach/thrust/releases/download/v0.7.6/thrust-v0.7.6-darwin-x64.zip and it worked fine after that. I'm on OSX 10.9.5.

**Comment by mallocator** [comment]
I'm having a similar issue - installation fails with code 9 on OSX.

In my case not even the node-thrust directory in node_modules is created. No idea where it's trying to save the zip file, but if it's not there it obviously can't extract 

Creating the directory ./node_modules/node-thrust/vendor/thrust/ before running npm didn't fix it either unfortunately.

**Comment by rumkin** [comment]
Got the same error on MacOS 10.9. Solved with manual installation:

``` shell
git clone https://github.com/breach/node-thrust.git
npm install ./node-thrust
```
